version: "3.3"

networks:
  video_network:

volumes:
  data:
  redis_data:

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"
    networks:
      - video_network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - video_network
    volumes:
      - data:/var/lib/mysql
      - ./video.sql:/docker-entrypoint-initdb.d/video.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=video"

  redis:
    image: redis:5.0.10
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

#  nginx:
#    image: nginx:1.21.6
#    ports:
#      - "80:80"
#    volumes:
#      - ./admin-dist:/usr/share/nginx/html:ro

################# 部署 ##################
#  admins:
#    build:
#      context: ./images/admins
#      dockerfile: Dockerfile
#    ports:
#    - "9001:9001"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#  category:
#    build:
#      context: ./images/categorys
#      dockerfile: Dockerfile
#    ports:
#    - "9002:9002"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#  gateway:
#    build:
#      context: ./images/gateway
#      dockerfile: Dockerfile
#    ports:
#    - "9000:9000"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#  users:
#    build:
#      context: ./images/users
#      dockerfile: Dockerfile
#    ports:
#    - "9003:9003"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#  videos:
#    build:
#      context: ./images/videos
#      dockerfile: Dockerfile
#    ports:
#    - "9004:9004"
#    depends_on:
#      - mysql
#      - redis
#      - nacos