version: "3.3"

networks:
  video_network:

volumes:
  data:
  redis_data:

services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"
      - "SPRING_DATASOURCE_PLATFORM=mysql"
      - "MYSQL_SERVICE_HOST=192.168.150.3"
      - "MYSQL_SERVICE_USER=root"
      - "MYSQL_SERVICE_PASSWORD=123456"
      - "MYSQL_SERVICE_DB_NAME=nacos_config"
    networks:
      - video_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - video_network
    volumes:
      - data:/var/lib/mysql
      - ./video.sql:/docker-entrypoint-initdb.d/video.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=video"

  redis:
    image: redis:5.0.10
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.7.28-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - video_network
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=123456"

  seata-server:
    image: seataio/seata-server:1.5.0
    container_name: seata-server
    ports:
      - "8091:8091"
    networks:
      - video_network

    volumes:
      - /home/lww/seata/seata-server:/seata-server
    environment:
      - SEATA_PORT=8091
      - SEATA_IP=192.168.150.3
    depends_on:
      - nacos

  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - video_network
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /home/lww/elasticsearch/data:/usr/share/elasticsearch/data
      - /home/lww/elasticsearch/config:/usr/share/elasticsearch/config
      - /home/lww/elasticsearch/plugins:/usr/share/elasticsearch/plugins

  kibana:
    image: kibana:7.14.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - video_network
    volumes:
      - /home/lww/kibana/config:/usr/share/kibana/config


#  nginx:
#    image: nginx:1.21.6
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./admin-dist:/usr/share/nginx/html:ro

################# 部署 ##################
#  admins:
#    build:
#      context: ./images/admins
#      dockerfile: Dockerfile
#    ports:
#    - "9001:9001"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#  category:
#    build:
#      context: ./images/categorys
#      dockerfile: Dockerfile
#    ports:
#    - "9002:9002"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#  gateway:
#    build:
#      context: ./images/gateway
#      dockerfile: Dockerfile
#    ports:
#    - "9000:9000"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#  users:
#    build:
#      context: ./images/users
#      dockerfile: Dockerfile
#    ports:
#    - "9003:9003"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#  videos:
#    build:
#      context: ./images/videos
#      dockerfile: Dockerfile
#    ports:
#    - "9004:9004"
#    depends_on:
#      - mysql
#      - redis
#      - nacos