server:
  port: 9005
spring:
  application:
    name: VIDEO-API-CATEGORIES
  cloud:
    nacos:
      server-addr: 192.168.150.3:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.150.3:3306/video?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456


logging:
  level:
    top.liguapi.api.mapper: debug


seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      serverAddr: 192.168.150.3:8848
      group: SEATA_GROUP
      namespace:
      cluster: default
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.150.3:8848
      namespace:
      group: SEATA_GROUP
      username: nacos
      password: nacos
      dataId: seataServer.properties
